version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: marcos-geodesicos-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: marcos123
      POSTGRES_DB: marcos_geodesicos
      PGDATA: /var/lib/postgresql/data/pgdata

    ports:
      - "5434:5432"

    volumes:
      - postgres_data_marcos:/var/lib/postgresql/data
      - ./backend/backups:/backups

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d marcos_geodesicos"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_marcos:
    driver: local
